# basic options
title: Subbiani
author: Joe Subbiani
email: joe.subbiani@gmail.com
description: Description
github_username: JoeSubbi
github:
  public: true
  is_project_page: false
  owner_url: https://github.com/JoeSubbi

# build settings
markdown: kramdown
theme: jekyll-theme-tactile